%% Phase 2 Mechanical Plant Evidence Generation
% Model-Based Electric Drive Control & Virtual Verification Platform
%
% Purpose:
% Generate reproducible Phase 2 engineering evidence after successful
% mechanical-plant verification.
%
% Outputs:
%   - Raw MATLAB results (.mat)
%   - Scenario datasets (.csv)
%   - Verification summary (.csv)
%   - Velocity response plot (.png)
%   - Acceleration response plot (.png)
%   - Verification report (.txt)

%% Initialization

clearvars;
clc;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PHASE 2 MECHANICAL EVIDENCE GENERATION\n');
fprintf('============================================================\n');

%% Determine project paths

scriptFilePath = mfilename('fullpath');
analysisDirectory = fileparts(scriptFilePath);

matlabDirectory = fileparts(analysisDirectory);
projectRoot = fileparts(matlabDirectory);

configDirectory = fullfile(projectRoot, 'config');
modelDirectory = fullfile(projectRoot, 'models');
resultsDirectory = fullfile(projectRoot, 'results', 'mechanical');

configFile = fullfile(configDirectory, 'init_project.m');

modelName = "agv_mechanical_plant";
modelFile = fullfile(modelDirectory, modelName + ".slx");

%% Validate required files

if ~isfile(configFile)
    error( ...
        'Phase2Evidence:MissingConfiguration', ...
        'Configuration file not found:\n%s', ...
        configFile);
end

if ~isfile(modelFile)
    error( ...
        'Phase2Evidence:MissingModel', ...
        'Simulink model not found:\n%s', ...
        modelFile);
end

%% Create results directory if required

if ~isfolder(resultsDirectory)
    mkdir(resultsDirectory);
end

%% Add project directories

addpath(configDirectory);
addpath(modelDirectory);

%% Load nominal configuration

run(configFile);

nominalCfg = cfg;

%% Load model

load_system(modelFile);

%% Common plant quantities

driveForce = ...
    cfg.test.phase2.motor_torque * ...
    cfg.drivetrain.gear_ratio * ...
    cfg.drivetrain.efficiency / ...
    cfg.agv.wheel_radius;

resistanceCoefficient = ...
    cfg.agv.resistance_coefficient;

torqueStepTime = ...
    cfg.test.phase2.torque_step_time;

loadStepTime = ...
    cfg.test.phase2.load_step_time;

%% Verification settings

verification.standardTime = 2.5;      % [s]
verification.preLoadTime = 1.5;       % [s]
verification.postLoadTime = 3.0;      % [s]

verification.velocityTolerance = 1e-3;       % [m/s]
verification.accelerationTolerance = 1e-3;   % [m/s^2]

%% ============================================================
% M0 - NOMINAL BASELINE
% =============================================================

cfg = nominalCfg;

cfg.agv.mass = 200.0;                 % [kg]
cfg.test.phase2.load_force = 0.0;     % [N]

tauM0 = ...
    cfg.agv.mass / resistanceCoefficient;

steadyVelocityM0 = ...
    driveForce / resistanceCoefficient;

elapsedM0 = ...
    verification.standardTime - torqueStepTime;

expectedVelocityM0 = ...
    steadyVelocityM0 * ...
    (1 - exp(-elapsedM0 / tauM0));

expectedAccelerationM0 = ...
    (driveForce / cfg.agv.mass) * ...
    exp(-elapsedM0 / tauM0);

simOutM0 = sim(modelName);

speedLogM0 = simOutM0.get('speed_log');
accelLogM0 = simOutM0.get('accel_log');

measuredVelocityM0 = interp1( ...
    speedLogM0.Time, ...
    speedLogM0.Data, ...
    verification.standardTime, ...
    'linear');

measuredAccelerationM0 = interp1( ...
    accelLogM0.Time, ...
    accelLogM0.Data, ...
    verification.standardTime, ...
    'linear');

velocityErrorM0 = ...
    abs(measuredVelocityM0 - expectedVelocityM0);

accelerationErrorM0 = ...
    abs(measuredAccelerationM0 - expectedAccelerationM0);

passM0 = ...
    velocityErrorM0 <= verification.velocityTolerance && ...
    accelerationErrorM0 <= verification.accelerationTolerance;

dataM0 = table( ...
    speedLogM0.Time, ...
    speedLogM0.Data, ...
    accelLogM0.Data, ...
    'VariableNames', ...
    {'Time_s', 'Velocity_mps', 'Acceleration_mps2'});

%% ============================================================
% M1 - PAYLOAD INCREASE
% =============================================================

cfg = nominalCfg;

cfg.agv.mass = 300.0;                 % [kg]
cfg.test.phase2.load_force = 0.0;     % [N]

tauM1 = ...
    cfg.agv.mass / resistanceCoefficient;

steadyVelocityM1 = ...
    driveForce / resistanceCoefficient;

elapsedM1 = ...
    verification.standardTime - torqueStepTime;

expectedVelocityM1 = ...
    steadyVelocityM1 * ...
    (1 - exp(-elapsedM1 / tauM1));

expectedAccelerationM1 = ...
    (driveForce / cfg.agv.mass) * ...
    exp(-elapsedM1 / tauM1);

simOutM1 = sim(modelName);

speedLogM1 = simOutM1.get('speed_log');
accelLogM1 = simOutM1.get('accel_log');

measuredVelocityM1 = interp1( ...
    speedLogM1.Time, ...
    speedLogM1.Data, ...
    verification.standardTime, ...
    'linear');

measuredAccelerationM1 = interp1( ...
    accelLogM1.Time, ...
    accelLogM1.Data, ...
    verification.standardTime, ...
    'linear');

velocityErrorM1 = ...
    abs(measuredVelocityM1 - expectedVelocityM1);

accelerationErrorM1 = ...
    abs(measuredAccelerationM1 - expectedAccelerationM1);

passM1 = ...
    velocityErrorM1 <= verification.velocityTolerance && ...
    accelerationErrorM1 <= verification.accelerationTolerance;

dataM1 = table( ...
    speedLogM1.Time, ...
    speedLogM1.Data, ...
    accelLogM1.Data, ...
    'VariableNames', ...
    {'Time_s', 'Velocity_mps', 'Acceleration_mps2'});

%% ============================================================
% M2 - EXTERNAL LOAD DISTURBANCE
% =============================================================

cfg = nominalCfg;

cfg.agv.mass = 200.0;                 % [kg]
cfg.test.phase2.load_force = 100.0;   % [N]

tauM2 = ...
    cfg.agv.mass / resistanceCoefficient;

steadyVelocityBeforeLoad = ...
    driveForce / resistanceCoefficient;

%% Pre-load analytical response

elapsedPreLoad = ...
    verification.preLoadTime - torqueStepTime;

expectedVelocityPreLoad = ...
    steadyVelocityBeforeLoad * ...
    (1 - exp(-elapsedPreLoad / tauM2));

expectedAccelerationPreLoad = ...
    (driveForce / cfg.agv.mass) * ...
    exp(-elapsedPreLoad / tauM2);

%% Velocity at load-step instant

elapsedToLoadStep = ...
    loadStepTime - torqueStepTime;

velocityAtLoadStep = ...
    steadyVelocityBeforeLoad * ...
    (1 - exp(-elapsedToLoadStep / tauM2));

%% Post-load analytical response

steadyVelocityAfterLoad = ...
    (driveForce - cfg.test.phase2.load_force) / ...
    resistanceCoefficient;

elapsedPostLoad = ...
    verification.postLoadTime - loadStepTime;

expectedVelocityPostLoad = ...
    steadyVelocityAfterLoad + ...
    (velocityAtLoadStep - steadyVelocityAfterLoad) * ...
    exp(-elapsedPostLoad / tauM2);

expectedAccelerationPostLoad = ...
    ( ...
    driveForce - ...
    cfg.test.phase2.load_force - ...
    resistanceCoefficient * expectedVelocityPostLoad ...
    ) / cfg.agv.mass;

%% Simulate M2

simOutM2 = sim(modelName);

speedLogM2 = simOutM2.get('speed_log');
accelLogM2 = simOutM2.get('accel_log');

measuredVelocityPreLoad = interp1( ...
    speedLogM2.Time, ...
    speedLogM2.Data, ...
    verification.preLoadTime, ...
    'linear');

measuredAccelerationPreLoad = interp1( ...
    accelLogM2.Time, ...
    accelLogM2.Data, ...
    verification.preLoadTime, ...
    'linear');

measuredVelocityPostLoad = interp1( ...
    speedLogM2.Time, ...
    speedLogM2.Data, ...
    verification.postLoadTime, ...
    'linear');

measuredAccelerationPostLoad = interp1( ...
    accelLogM2.Time, ...
    accelLogM2.Data, ...
    verification.postLoadTime, ...
    'linear');

velocityErrorPreLoad = ...
    abs(measuredVelocityPreLoad - expectedVelocityPreLoad);

accelerationErrorPreLoad = ...
    abs(measuredAccelerationPreLoad - expectedAccelerationPreLoad);

velocityErrorPostLoad = ...
    abs(measuredVelocityPostLoad - expectedVelocityPostLoad);

accelerationErrorPostLoad = ...
    abs(measuredAccelerationPostLoad - expectedAccelerationPostLoad);

passM2Pre = ...
    velocityErrorPreLoad <= verification.velocityTolerance && ...
    accelerationErrorPreLoad <= verification.accelerationTolerance;

passM2Post = ...
    velocityErrorPostLoad <= verification.velocityTolerance && ...
    accelerationErrorPostLoad <= verification.accelerationTolerance;

passM2 = ...
    passM2Pre && passM2Post;

dataM2 = table( ...
    speedLogM2.Time, ...
    speedLogM2.Data, ...
    accelLogM2.Data, ...
    'VariableNames', ...
    {'Time_s', 'Velocity_mps', 'Acceleration_mps2'});

%% ============================================================
% VERIFICATION SUMMARY
% =============================================================

scenario = [
    "M0_Nominal"
    "M1_Payload"
    "M2_PreLoad"
    "M2_PostLoad"
];

verificationTime_s = [
    verification.standardTime
    verification.standardTime
    verification.preLoadTime
    verification.postLoadTime
];

expectedVelocity_mps = [
    expectedVelocityM0
    expectedVelocityM1
    expectedVelocityPreLoad
    expectedVelocityPostLoad
];

measuredVelocity_mps = [
    measuredVelocityM0
    measuredVelocityM1
    measuredVelocityPreLoad
    measuredVelocityPostLoad
];

velocityError_mps = [
    velocityErrorM0
    velocityErrorM1
    velocityErrorPreLoad
    velocityErrorPostLoad
];

expectedAcceleration_mps2 = [
    expectedAccelerationM0
    expectedAccelerationM1
    expectedAccelerationPreLoad
    expectedAccelerationPostLoad
];

measuredAcceleration_mps2 = [
    measuredAccelerationM0
    measuredAccelerationM1
    measuredAccelerationPreLoad
    measuredAccelerationPostLoad
];

accelerationError_mps2 = [
    accelerationErrorM0
    accelerationErrorM1
    accelerationErrorPreLoad
    accelerationErrorPostLoad
];

status = [
    string(passM0)
    string(passM1)
    string(passM2Pre)
    string(passM2Post)
];

status(status == "1") = "PASS";
status(status == "0") = "FAIL";

summaryTable = table( ...
    scenario, ...
    verificationTime_s, ...
    expectedVelocity_mps, ...
    measuredVelocity_mps, ...
    velocityError_mps, ...
    expectedAcceleration_mps2, ...
    measuredAcceleration_mps2, ...
    accelerationError_mps2, ...
    status);

overallPass = ...
    passM0 && ...
    passM1 && ...
    passM2;

%% ============================================================
% SAVE RAW DATA
% =============================================================

phase2Evidence = struct();

phase2Evidence.configuration = nominalCfg;
phase2Evidence.verification = verification;

phase2Evidence.M0.data = dataM0;
phase2Evidence.M1.data = dataM1;
phase2Evidence.M2.data = dataM2;

phase2Evidence.summary = summaryTable;
phase2Evidence.overallPass = overallPass;

save( ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_phase2_results.mat'), ...
    'phase2Evidence');

%% Save scenario CSV datasets

writetable( ...
    dataM0, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_M0_nominal.csv'));

writetable( ...
    dataM1, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_M1_payload.csv'));

writetable( ...
    dataM2, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_M2_load_disturbance.csv'));

%% Save verification summary

writetable( ...
    summaryTable, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_scenario_summary.csv'));

%% ============================================================
% VELOCITY RESPONSE PLOT
% =============================================================

velocityFigure = figure( ...
    'Name', ...
    'AGV Mechanical Velocity Response');

plot( ...
    speedLogM0.Time, ...
    speedLogM0.Data, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    speedLogM1.Time, ...
    speedLogM1.Data, ...
    'LineWidth', 1.5);

plot( ...
    speedLogM2.Time, ...
    speedLogM2.Data, ...
    'LineWidth', 1.5);
xline(cfg.test.phase2.torque_step_time, '--', 'Torque step');
xline(cfg.test.phase2.load_step_time, '--', 'Load step');
grid on;

xlabel('Time [s]');
ylabel('Vehicle Velocity [m/s]');

title('AGV Mechanical Plant - Open-Loop Velocity Response');

legend( ...
    'M0 Nominal', ...
    'M1 Payload Increase', ...
    'M2 Load Disturbance', ...
    'Location', 'best');

exportgraphics( ...
    velocityFigure, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_velocity_response.png'), ...
    'Resolution', 300);

%% ============================================================
% ACCELERATION RESPONSE PLOT
% =============================================================

accelerationFigure = figure( ...
    'Name', ...
    'AGV Mechanical Acceleration Response');

plot( ...
    accelLogM0.Time, ...
    accelLogM0.Data, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    accelLogM1.Time, ...
    accelLogM1.Data, ...
    'LineWidth', 1.5);

plot( ...
    accelLogM2.Time, ...
    accelLogM2.Data, ...
    'LineWidth', 1.5);
xline(cfg.test.phase2.torque_step_time, '--', 'Torque step');
xline(cfg.test.phase2.load_step_time, '--', 'Load step');
grid on;

xlabel('Time [s]');
ylabel('Vehicle Acceleration [m/s^2]');

title('AGV Mechanical Plant - Open-Loop Acceleration Response');

legend( ...
    'M0 Nominal', ...
    'M1 Payload Increase', ...
    'M2 Load Disturbance', ...
    'Location', 'best');

exportgraphics( ...
    accelerationFigure, ...
    fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_acceleration_response.png'), ...
    'Resolution', 300);

%% ============================================================
% VERIFICATION REPORT
% =============================================================

reportFile = fullfile( ...
    resultsDirectory, ...
    'agv_mechanical_verification_report.txt');

reportID = fopen(reportFile, 'w');

if reportID == -1
    error( ...
        'Phase2Evidence:ReportCreationFailed', ...
        'Unable to create verification report.');
end

fprintf(reportID, ...
    'MODEL-BASED ELECTRIC DRIVE CONTROL & VIRTUAL VERIFICATION PLATFORM\n');

fprintf(reportID, ...
    'PHASE 2 - AGV MECHANICAL PLANT VERIFICATION REPORT\n');

fprintf(reportID, ...
    '============================================================\n\n');

fprintf(reportID, ...
    'Plant equation:\n');

fprintf(reportID, ...
    'm*dv/dt = F_drive - F_load - b*v\n\n');

fprintf(reportID, ...
    'Nominal vehicle mass       : %.2f kg\n', ...
    nominalCfg.agv.mass);

fprintf(reportID, ...
    'Wheel radius               : %.3f m\n', ...
    nominalCfg.agv.wheel_radius);

fprintf(reportID, ...
    'Gear ratio                 : %.2f : 1\n', ...
    nominalCfg.drivetrain.gear_ratio);

fprintf(reportID, ...
    'Drivetrain efficiency      : %.2f %%\n', ...
    nominalCfg.drivetrain.efficiency * 100);

fprintf(reportID, ...
    'Resistance coefficient     : %.2f N*s/m\n', ...
    nominalCfg.agv.resistance_coefficient);

fprintf(reportID, ...
    'Drive force                : %.2f N\n\n', ...
    driveForce);

fprintf(reportID, ...
    'Scenario Verification\n');

fprintf(reportID, ...
    '------------------------------------------------------------\n');

for rowIndex = 1:height(summaryTable)

    fprintf(reportID, ...
        '%-18s  Velocity Error: %.6f m/s  Accel Error: %.6f m/s^2  %s\n', ...
        summaryTable.scenario(rowIndex), ...
        summaryTable.velocityError_mps(rowIndex), ...
        summaryTable.accelerationError_mps2(rowIndex), ...
        summaryTable.status(rowIndex));
end

fprintf(reportID, ...
    '\n------------------------------------------------------------\n');

if overallPass
    fprintf(reportID, 'OVERALL RESULT: PASS\n');
else
    fprintf(reportID, 'OVERALL RESULT: FAIL\n');
end

fclose(reportID);

%% Close Simulink model

close_system(modelName, 0);

%% Final evidence-generation summary

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PHASE 2 EVIDENCE PACKAGE GENERATED\n');
fprintf('============================================================\n');

fprintf('Results directory:\n%s\n\n', resultsDirectory);

fprintf('Raw MAT results              : SAVED\n');
fprintf('Scenario CSV datasets        : SAVED\n');
fprintf('Verification summary CSV     : SAVED\n');
fprintf('Velocity response plot       : SAVED\n');
fprintf('Acceleration response plot   : SAVED\n');
fprintf('Verification report          : SAVED\n');

fprintf('------------------------------------------------------------\n');

if overallPass
    fprintf('Evidence verification status : PASS\n');
else
    fprintf('Evidence verification status : FAIL\n');
end

fprintf('============================================================\n\n');

assert( ...
    overallPass, ...
    'Phase2Evidence:VerificationFailed', ...
    'Evidence generation completed, but verification did not pass.');